### ISSUE TITLE
0.0.5: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [andrew-d/python-multipart#44] opened 2022-01-21 14:41 UTC
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-multipart-0.0.5-13.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-multipart-0.0.5-13.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/python-multipart-0.0.5
plugins: cov-3.0.0, anyio-3.3.4
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
____________________________________________________________ ERROR collecting multipart/tests/test_multipart.py ____________________________________________________________
multipart/tests/test_multipart.py:715: in <module>
    yaml_data = yaml.load(f)
E   TypeError: load() missing 1 required positional argument: 'Loader'
============================================================================= warnings summary =============================================================================
multipart/tests/compat.py:48
  /home/tkloczko/rpmbuild/BUILD/python-multipart-0.0.5/multipart/tests/compat.py:48: PytestUnknownMarkWarning: Unknown pytest.mark.slow_test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    slow_test = pytest.mark.slow_test

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
ERROR multipart/tests/test_multipart.py - TypeError: load() missing 1 required positional argument: 'Loader'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 warning, 1 error in 0.37s ========================================================================
```

**Comment by Apteryks** [comment] 2022-04-19 20:13
This is a duplicate of #41

**Comment by mgorny** [comment] 2022-11-21 11:35
@andrew-d, could you please make a new release?

**Closed** 2023-02-27 16:37 UTC
