### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [andrew-d/python-multipart#37] opened 2021-06-08 15:52 UTC
Wheels (`.whl`) for this package are [currently missing from PyPI](https://pypi.org/project/python-multipart/#files). Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by axelfauvel** [comment] 2021-07-07 09:51
Hi there,

I have an issue with `python-multipart` in poetry. When I add `python-multipart` in poetry dependencies, it breaks dependency calculation.

I'm guessing that missing `.whl` can be related to this issue.

I'm going to try to publish wheel file on our private registry and will keep you posted if it helps solving my probelm.

**Comment by axelfauvel** [comment] 2021-07-07 14:16
nevermind, it's absolutely not related

**Comment by la4de** [comment] 2021-11-20 19:45
Installing `python-multipart` to pyodide fails due missing wheel distribution. It would be nice to get that fixed.

I'm getting following error
```
  File "/lib/python3.9/site-packages/micropip/micropip.py", line 242, in add_requirement
    await self.add_wheel(req.name, wheel, ver, req.extras, ctx, transaction)
  File "/lib/python3.9/site-packages/micropip/micropip.py", line 253, in add_wheel
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.9/site-packages/micropip/micropip.py", line 241, in add_requirement
    wheel, ver = self.find_wheel(metadata, req)
  File "/lib/python3.9/site-packages/micropip/micropip.py", line 269, in find_wheel
    raise ValueError(f"Couldn't find a pure Python 3 wheel for '{req}'")
ValueError: Couldn't find a pure Python 3 wheel for 'python-multipart<0.0.6,>=0.0.5'
```

**Comment by axelfauvel** [comment] 2022-11-02 08:05
@Ambro17 : are we sure this repo is maintained and PR will be merged ?

If so, I can do it

**Comment by Ambro17** [comment] 2022-11-02 12:56
No, i'm not sure but it's a dependency on the third most used web framework in python so i think it's worth the try

**Comment by tomchristie** [comment] 2022-11-03 12:42
Conditions look favorable.

**Comment by axelfauvel** [comment] 2022-11-03 13:17
Hi @tomchristie, I'm having a look at the CI part of this repo and can't find anything related to package build.

Do you know how build is currently done ?

**Comment by tomchristie** [comment] 2022-11-03 14:22
Hrmm, it's been a while... https://pypi.org/project/python-multipart/#history

I assume we've always released manually in the past.

The instructions at the top of this thread look useful. https://github.com/andrew-d/python-multipart/issues/37#issue-915200579

**Comment by Ambro17** [comment] 2022-11-03 14:31
This section of the tutorial might be relevant too. Packaging in python has improved a lot lately so one can not depend on setuptools if one doesn't want to. `python -m build` can build both source and wheel distributions. More details on the link
https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives

**Comment by axelfauvel** [comment] 2022-11-03 14:31
Yep, this is the way :)

What i can do in the PR is add an action when a tag is pushed to the repo that will build & publish package to PyPi.

What do you think about that?

**Comment by axelfauvel** [comment] 2022-11-03 14:35
> This section of the tutorial might be relevant too. Packaging in python has improved a lot lately so one can not depend on setuptools if one doesn't want to. `python -m build` can build both source and wheel distributions. More details on the link https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives

I just saw that this issue got opened today : https://github.com/andrew-d/python-multipart/issues/50

Could be a good idea as you suggested to also move setup.py to pyproject.toml

**Comment by axelfauvel** [comment] 2022-11-03 16:06
First PR opened : https://github.com/andrew-d/python-multipart/pull/52

Review appreciated :)

**Comment by tomchristie** [comment] 2022-11-25 14:30
Prompted by https://github.com/andrew-d/python-multipart/issues/40#issuecomment-1327520773

Supposing we wanted pushed a new release now...

* Which currently outstanding issues would that close?
* What would the release notes be?

**Comment by nlhnt** [comment] 2022-11-25 22:58
@tomchristie latest relase (0.0.5) is based on py==1.10 which has a reported, unclosed CVE.

**Comment by ghandic** [comment] 2023-02-15 13:03
Any progress on this?

**Comment by Kludex** [comment] 2023-02-15 13:07
give me 10 min, hold on

**Comment by ghandic** [comment] 2023-02-15 13:30
Automated? I'm using pants on an M1 and it requires wheels, at the moment I'm just vendoring it myself so no rush :)

**Comment by Kludex** [comment] 2023-02-15 13:35
I was going to make a manual release, since we can't use this flow: https://github.com/andrew-d/python-multipart/pull/57

If you have a suggestion about a flow that could work, and want to push a PR, I'd check it... :eyes:

**Comment by ghandic** [comment] 2023-02-15 13:51
On tag? 

The issue is that you can't make releases on @andrew-d 's repo?

**Comment by Kludex** [comment] 2023-02-15 13:56
> On tag?

That would work, yep.

> The issue is that you can't make releases on @andrew-d 's repo?

Yep.

**Comment by ghandic** [comment] 2023-02-15 22:51
Did you want a PR raised to change this to be release on tag?

**Comment by Kludex** [comment] 2023-02-27 16:23
> Did you want a PR raised to change this to be release on tag?

Thanks, but @Ambro17 implemented it on https://github.com/andrew-d/python-multipart/pull/57 :pray: 

@ghandic sorry for the delay... Hard time on personal life...

I'm making the release now.

**Closed** 2023-02-27 16:37 UTC

**Comment by Daviid-P** [comment] 2024-04-03 20:56
I just did `poetry add python-multipart@latest` and got

```
poetry add python-multipart@latest
Using version ^0.0.9 for python-multipart

Updating dependencies
Resolving dependencies... (6.5s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing python-multipart (0.0.9)
```
But my `pyproject.toml` looks like

`python-multipart = "^1.0.9"`

is it 1.0.9 or 0.0.9


I tried 0.0.9 manually before but got an error on `poetry install`

```
SolverProblemError

  Because project depends on python-multipart (^0.0.9) which doesn't match any versions, version solving failed.

  at /usr/lib/python3/dist-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```
